<?php

return [
    ['name' => 'Afghanistan', 'iso_2' => 'AF', 'iso_3' => 'AFG', 'code' => '004'],
    ['name' => 'Åland Islands', 'iso_2' => 'AX', 'iso_3' => 'ALA', 'code' => '248'],
    ['name' => 'Albania', 'iso_2' => 'AL', 'iso_3' => 'ALB', 'code' => '008'],
    ['name' => 'Algeria', 'iso_2' => 'DZ', 'iso_3' => 'DZA', 'code' => '012'],
    ['name' => 'American Samoa', 'iso_2' => 'AS', 'iso_3' => 'ASM', 'code' => '016'],
    ['name' => 'Andorra', 'iso_2' => 'AD', 'iso_3' => 'AND', 'code' => '020'],
    ['name' => 'Angola', 'iso_2' => 'AO', 'iso_3' => 'AGO', 'code' => '024'],
    ['name' => 'Anguilla', 'iso_2' => 'AI', 'iso_3' => 'AIA', 'code' => '660'],
    ['name' => 'Antarctica', 'iso_2' => 'AQ', 'iso_3' => 'ATA', 'code' => '010'],
    ['name' => 'Antigua and Barbuda', 'iso_2' => 'AG', 'iso_3' => 'ATG', 'code' => '028'],
    ['name' => 'Argentina', 'iso_2' => 'AR', 'iso_3' => 'ARG', 'code' => '032'],
    ['name' => 'Armenia', 'iso_2' => 'AM', 'iso_3' => 'ARM', 'code' => '051'],
    ['name' => 'Aruba', 'iso_2' => 'AW', 'iso_3' => 'ABW', 'code' => '533'],
    ['name' => 'Australia', 'iso_2' => 'AU', 'iso_3' => 'AUS', 'code' => '036'],
    ['name' => 'Austria', 'iso_2' => 'AT', 'iso_3' => 'AUT', 'code' => '040'],
    ['name' => 'Azerbaijan', 'iso_2' => 'AZ', 'iso_3' => 'AZE', 'code' => '031'],
    ['name' => 'Bahamas', 'iso_2' => 'BS', 'iso_3' => 'BHS', 'code' => '044'],
    ['name' => 'Bahrain', 'iso_2' => 'BH', 'iso_3' => 'BHR', 'code' => '048'],
    ['name' => 'Bangladesh', 'iso_2' => 'BD', 'iso_3' => 'BGD', 'code' => '050'],
    ['name' => 'Barbados', 'iso_2' => 'BB', 'iso_3' => 'BRB', 'code' => '052'],
    ['name' => 'Belarus', 'iso_2' => 'BY', 'iso_3' => 'BLR', 'code' => '112'],
    ['name' => 'Belgium', 'iso_2' => 'BE', 'iso_3' => 'BEL', 'code' => '056'],
    ['name' => 'Belize', 'iso_2' => 'BZ', 'iso_3' => 'BLZ', 'code' => '084'],
    ['name' => 'Benin', 'iso_2' => 'BJ', 'iso_3' => 'BEN', 'code' => '204'],
    ['name' => 'Bermuda', 'iso_2' => 'BM', 'iso_3' => 'BMU', 'code' => '060'],
    ['name' => 'Bhutan', 'iso_2' => 'BT', 'iso_3' => 'BTN', 'code' => '064'],
    ['name' => 'Bolivia', 'iso_2' => 'BO', 'iso_3' => 'BOL', 'code' => '068'],
    ['name' => 'Bosnia and Herzegovina', 'iso_2' => 'BA', 'iso_3' => 'BIH', 'code' => '070'],
    ['name' => 'Botswana', 'iso_2' => 'BW', 'iso_3' => 'BWA', 'code' => '072'],
    ['name' => 'Bouvet Island', 'iso_2' => 'BV', 'iso_3' => 'BVT', 'code' => '074'],
    ['name' => 'Brazil', 'iso_2' => 'BR', 'iso_3' => 'BRA', 'code' => '076'],
    ['name' => 'British Indian Ocean Territory', 'iso_2' => 'IO', 'iso_3' => 'IOT', 'code' => '086'],
    ['name' => 'Brunei Darussalam', 'iso_2' => 'BN', 'iso_3' => 'BRN', 'code' => '096'],
    ['name' => 'Bulgaria', 'iso_2' => 'BG', 'iso_3' => 'BGR', 'code' => '100'],
    ['name' => 'Burkina Faso', 'iso_2' => 'BF', 'iso_3' => 'BFA', 'code' => '854'],
    ['name' => 'Burundi', 'iso_2' => 'BI', 'iso_3' => 'BDI', 'code' => '108'],
    ['name' => 'Cambodia', 'iso_2' => 'KH', 'iso_3' => 'KHM', 'code' => '116'],
    ['name' => 'Cameroon', 'iso_2' => 'CM', 'iso_3' => 'CMR', 'code' => '120'],
    ['name' => 'Canada', 'iso_2' => 'CA', 'iso_3' => 'CAN', 'code' => '124'],
    ['name' => 'Cape Verde', 'iso_2' => 'CV', 'iso_3' => 'CPV', 'code' => '132'],
    ['name' => 'Cayman Islands', 'iso_2' => 'KY', 'iso_3' => 'CYM', 'code' => '136'],
    ['name' => 'Central African Republic', 'iso_2' => 'CF', 'iso_3' => 'CAF', 'code' => '140'],
    ['name' => 'Chad', 'iso_2' => 'TD', 'iso_3' => 'TCD', 'code' => '148'],
    ['name' => 'Chile', 'iso_2' => 'CL', 'iso_3' => 'CHL', 'code' => '152'],
    ['name' => 'China', 'iso_2' => 'CN', 'iso_3' => 'CHN', 'code' => '156'],
    ['name' => 'Christmas Island', 'iso_2' => 'CX', 'iso_3' => 'CXR', 'code' => '162'],
    ['name' => 'Cocos (Keeling) Islands', 'iso_2' => 'CC', 'iso_3' => 'CCK', 'code' => '166'],
    ['name' => 'Colombia', 'iso_2' => 'CO', 'iso_3' => 'COL', 'code' => '170'],
    ['name' => 'Comoros', 'iso_2' => 'KM', 'iso_3' => 'COM', 'code' => '174'],
    ['name' => 'Congo', 'iso_2' => 'CG', 'iso_3' => 'COG', 'code' => '178'],
    ['name' => 'The Democratic Republic of The Congo', 'iso_2' => 'CD', 'iso_3' => 'COD', 'code' => '180'],
    ['name' => 'Cook Islands', 'iso_2' => 'CK', 'iso_3' => 'COK', 'code' => '184'],
    ['name' => 'Costa Rica', 'iso_2' => 'CR', 'iso_3' => 'CRI', 'code' => '188'],
    ['name' => "Cote D'ivoire", 'iso_2' => 'CI', 'iso_3' => 'CIV', 'code' => '384'],
    ['name' => 'Croatia', 'iso_2' => 'HR', 'iso_3' => 'HRV', 'code' => '191'],
    ['name' => 'Cuba', 'iso_2' => 'CU', 'iso_3' => 'CUB', 'code' => '192'],
    ['name' => 'Cyprus', 'iso_2' => 'CY', 'iso_3' => 'CYP', 'code' => '196'],
    ['name' => 'Czech Republic', 'iso_2' => 'CZ', 'iso_3' => 'CZE', 'code' => '203'],
    ['name' => 'Denmark', 'iso_2' => 'DK', 'iso_3' => 'DNK', 'code' => '208'],
    ['name' => 'Djibouti', 'iso_2' => 'DJ', 'iso_3' => 'DJI', 'code' => '262'],
    ['name' => 'Dominica', 'iso_2' => 'DM', 'iso_3' => 'DMA', 'code' => '212'],
    ['name' => 'Dominican Republic', 'iso_2' => 'DO', 'iso_3' => 'DOM', 'code' => '214'],
    ['name' => 'Ecuador', 'iso_2' => 'EC', 'iso_3' => 'ECU', 'code' => '218'],
    ['name' => 'Egypt', 'iso_2' => 'EG', 'iso_3' => 'EGY', 'code' => '818'],
    ['name' => 'El Salvador', 'iso_2' => 'SV', 'iso_3' => 'SLV', 'code' => '222'],
    ['name' => 'Equatorial Guinea', 'iso_2' => 'GQ', 'iso_3' => 'GNQ', 'code' => '226'],
    ['name' => 'Eritrea', 'iso_2' => 'ER', 'iso_3' => 'ERI', 'code' => '232'],
    ['name' => 'Estonia', 'iso_2' => 'EE', 'iso_3' => 'EST', 'code' => '233'],
    ['name' => 'Ethiopia', 'iso_2' => 'ET', 'iso_3' => 'ETH', 'code' => '231'],
    ['name' => 'Falkland Islands (Malvinas)', 'iso_2' => 'FK', 'iso_3' => 'FLK', 'code' => '238'],
    ['name' => 'Faroe Islands', 'iso_2' => 'FO', 'iso_3' => 'FRO', 'code' => '234'],
    ['name' => 'Fiji', 'iso_2' => 'FJ', 'iso_3' => 'FJI', 'code' => '243'],
    ['name' => 'Finland', 'iso_2' => 'FI', 'iso_3' => 'FIN', 'code' => '246'],
    ['name' => 'France', 'iso_2' => 'FR', 'iso_3' => 'FRA', 'code' => '250'],
    ['name' => 'French Guiana', 'iso_2' => 'GF', 'iso_3' => 'GUF', 'code' => '254'],
    ['name' => 'French Polynesia', 'iso_2' => 'PF', 'iso_3' => 'PYF', 'code' => '258'],
    ['name' => 'French Southern Territories', 'iso_2' => 'TF', 'iso_3' => 'ATF', 'code' => '260'],
    ['name' => 'Gabon', 'iso_2' => 'GA', 'iso_3' => 'GAB', 'code' => '266'],
    ['name' => 'Gambia', 'iso_2' => 'GM', 'iso_3' => 'GMB', 'code' => '270'],
    ['name' => 'Georgia', 'iso_2' => 'GE', 'iso_3' => 'GEO', 'code' => '268'],
    ['name' => 'Germany', 'iso_2' => 'DE', 'iso_3' => 'DEU', 'code' => '276'],
    ['name' => 'Ghana', 'iso_2' => 'GH', 'iso_3' => 'GHA', 'code' => '288'],
    ['name' => 'Gibraltar', 'iso_2' => 'GI', 'iso_3' => 'GIB', 'code' => '292'],
    ['name' => 'Greece', 'iso_2' => 'GR', 'iso_3' => 'GRC', 'code' => '300'],
    ['name' => 'Greenland', 'iso_2' => 'GL', 'iso_3' => 'GRL', 'code' => '304'],
    ['name' => 'Grenada', 'iso_2' => 'GD', 'iso_3' => 'GRD', 'code' => '308'],
    ['name' => 'Guadeloupe', 'iso_2' => 'GP', 'iso_3' => 'GLP', 'code' => '312'],
    ['name' => 'Guam', 'iso_2' => 'GU', 'iso_3' => 'GUM', 'code' => '316'],
    ['name' => 'Guatemala', 'iso_2' => 'GT', 'iso_3' => 'GTM', 'code' => '320'],
    ['name' => 'Guernsey', 'iso_2' => 'GG', 'iso_3' => 'GGY', 'code' => '831'],
    ['name' => 'Guinea', 'iso_2' => 'GN', 'iso_3' => 'GIN', 'code' => '324'],
    ['name' => 'Guinea-bissau', 'iso_2' => 'GW', 'iso_3' => 'GNB', 'code' => '624'],
    ['name' => 'Guyana', 'iso_2' => 'GY', 'iso_3' => 'GUY', 'code' => '328'],
    ['name' => 'Haiti', 'iso_2' => 'HT', 'iso_3' => 'HTI', 'code' => '332'],
    ['name' => 'Heard Island and Mcdonald Islands', 'iso_2' => 'HM', 'iso_3' => 'HMD', 'code' => '334'],
    ['name' => 'Holy See (Vatican City State)', 'iso_2' => 'VA', 'iso_3' => 'VAT', 'code' => '336'],
    ['name' => 'Honduras', 'iso_2' => 'HN', 'iso_3' => 'HND', 'code' => '340'],
    ['name' => 'Hong Kong', 'iso_2' => 'HK', 'iso_3' => 'HKG', 'code' => '344'],
    ['name' => 'Hungary', 'iso_2' => 'HU', 'iso_3' => 'HUN', 'code' => '348'],
    ['name' => 'Iceland', 'iso_2' => 'IS', 'iso_3' => 'ISL', 'code' => '352'],
    ['name' => 'India', 'iso_2' => 'IN', 'iso_3' => 'IND', 'code' => '356'],
    ['name' => 'Indonesia', 'iso_2' => 'ID', 'iso_3' => 'IDN', 'code' => '360'],
    ['name' => 'Iran', 'iso_2' => 'IR', 'iso_3' => 'IRN', 'code' => '364'],
    ['name' => 'Iraq', 'iso_2' => 'IQ', 'iso_3' => 'IRQ', 'code' => '368'],
    ['name' => 'Ireland', 'iso_2' => 'IE', 'iso_3' => 'IRL', 'code' => '372'],
    ['name' => 'Isle of Man', 'iso_2' => 'IM', 'iso_3' => 'IMN', 'code' => '833'],
    ['name' => 'Israel', 'iso_2' => 'IL', 'iso_3' => 'ISR', 'code' => '376'],
    ['name' => 'Italy', 'iso_2' => 'IT', 'iso_3' => 'ITA', 'code' => '380'],
    ['name' => 'Jamaica', 'iso_2' => 'JM', 'iso_3' => 'JAM', 'code' => '388'],
    ['name' => 'Japan', 'iso_2' => 'JP', 'iso_3' => 'JPN', 'code' => '392'],
    ['name' => 'Jersey', 'iso_2' => 'JE', 'iso_3' => 'JEY', 'code' => '832'],
    ['name' => 'Jordan', 'iso_2' => 'JO', 'iso_3' => 'JOR', 'code' => '400'],
    ['name' => 'Kazakhstan', 'iso_2' => 'KZ', 'iso_3' => 'KAZ', 'code' => '398'],
    ['name' => 'Kenya', 'iso_2' => 'KE', 'iso_3' => 'KEN', 'code' => '404'],
    ['name' => 'Kiribati', 'iso_2' => 'KI', 'iso_3' => 'KIR', 'code' => '296'],
    ['name' => "Democratic People's Republic of Korea", 'iso_2' => 'KP', 'iso_3' => 'PRK', 'code' => '408'],
    ['name' => 'Republic of Korea', 'iso_2' => 'KR', 'iso_3' => 'KOR', 'code' => '410'],
    ['name' => 'Kuwait', 'iso_2' => 'KW', 'iso_3' => 'KWT', 'code' => '414'],
    ['name' => 'Kyrgyzstan', 'iso_2' => 'KG', 'iso_3' => 'KGZ', 'code' => '417'],
    ['name' => "Lao People's Democratic Republic", 'iso_2' => 'LA', 'iso_3' => 'LAO', 'code' => '418'],
    ['name' => 'Latvia', 'iso_2' => 'LV', 'iso_3' => 'LVA', 'code' => '428'],
    ['name' => 'Lebanon', 'iso_2' => 'LB', 'iso_3' => 'LBN', 'code' => '422'],
    ['name' => 'Lesotho', 'iso_2' => 'LS', 'iso_3' => 'LSO', 'code' => '426'],
    ['name' => 'Liberia', 'iso_2' => 'LR', 'iso_3' => 'LBR', 'code' => '430'],
    ['name' => 'Libya', 'iso_2' => 'LY', 'iso_3' => 'LBY', 'code' => '434'],
    ['name' => 'Liechtenstein', 'iso_2' => 'LI', 'iso_3' => 'LIE', 'code' => '438'],
    ['name' => 'Lithuania', 'iso_2' => 'LT', 'iso_3' => 'LTU', 'code' => '440'],
    ['name' => 'Luxembourg', 'iso_2' => 'LU', 'iso_3' => 'LUX', 'code' => '442'],
    ['name' => 'Macao', 'iso_2' => 'MO', 'iso_3' => 'MAC', 'code' => '446'],
    ['name' => 'Macedonia', 'iso_2' => 'MK', 'iso_3' => 'MKD', 'code' => '807'],
    ['name' => 'Madagascar', 'iso_2' => 'MG', 'iso_3' => 'MDG', 'code' => '450'],
    ['name' => 'Malawi', 'iso_2' => 'MW', 'iso_3' => 'MWI', 'code' => '454'],
    ['name' => 'Malaysia', 'iso_2' => 'MY', 'iso_3' => 'MYS', 'code' => '458'],
    ['name' => 'Maldives', 'iso_2' => 'MV', 'iso_3' => 'MDV', 'code' => '462'],
    ['name' => 'Mali', 'iso_2' => 'ML', 'iso_3' => 'MLI', 'code' => '466'],
    ['name' => 'Malta', 'iso_2' => 'MT', 'iso_3' => 'MLT', 'code' => '470'],
    ['name' => 'Marshall Islands', 'iso_2' => 'MH', 'iso_3' => 'MHL', 'code' => '584'],
    ['name' => 'Martinique', 'iso_2' => 'MQ', 'iso_3' => 'MTQ', 'code' => '474'],
    ['name' => 'Mauritania', 'iso_2' => 'MR', 'iso_3' => 'MRT', 'code' => '478'],
    ['name' => 'Mauritius', 'iso_2' => 'MU', 'iso_3' => 'MUS', 'code' => '480'],
    ['name' => 'Mayotte', 'iso_2' => 'YT', 'iso_3' => 'MYT', 'code' => '175'],
    ['name' => 'Mexico', 'iso_2' => 'MX', 'iso_3' => 'MEX', 'code' => '484'],
    ['name' => 'Micronesia', 'iso_2' => 'FM', 'iso_3' => 'FSM', 'code' => '583'],
    ['name' => 'Moldova', 'iso_2' => 'MD', 'iso_3' => 'MDA', 'code' => '498'],
    ['name' => 'Monaco', 'iso_2' => 'MC', 'iso_3' => 'MCO', 'code' => '492'],
    ['name' => 'Mongolia', 'iso_2' => 'MN', 'iso_3' => 'MNG', 'code' => '496'],
    ['name' => 'Montenegro', 'iso_2' => 'ME', 'iso_3' => 'MNE', 'code' => '499'],
    ['name' => 'Montserrat', 'iso_2' => 'MS', 'iso_3' => 'MSR', 'code' => '500'],
    ['name' => 'Morocco', 'iso_2' => 'MA', 'iso_3' => 'MAR', 'code' => '504'],
    ['name' => 'Mozambique', 'iso_2' => 'MZ', 'iso_3' => 'MOZ', 'code' => '508'],
    ['name' => 'Myanmar', 'iso_2' => 'MM', 'iso_3' => 'MMR', 'code' => '104'],
    ['name' => 'Namibia', 'iso_2' => 'NA', 'iso_3' => 'NAM', 'code' => '516'],
    ['name' => 'Nauru', 'iso_2' => 'NR', 'iso_3' => 'NRU', 'code' => '520'],
    ['name' => 'Nepal', 'iso_2' => 'NP', 'iso_3' => 'NPL', 'code' => '524'],
    ['name' => 'Netherlands', 'iso_2' => 'NL', 'iso_3' => 'NLD', 'code' => '528'],
    ['name' => 'Netherlands Antilles', 'iso_2' => 'AN', 'iso_3' => 'ANT', 'code' => '530'],
    ['name' => 'New Caledonia', 'iso_2' => 'NC', 'iso_3' => 'NCL', 'code' => '540'],
    ['name' => 'New Zealand', 'iso_2' => 'NZ', 'iso_3' => 'NZL', 'code' => '554'],
    ['name' => 'Nicaragua', 'iso_2' => 'NI', 'iso_3' => 'NIC', 'code' => '558'],
    ['name' => 'Niger', 'iso_2' => 'NE', 'iso_3' => 'NER', 'code' => '562'],
    ['name' => 'Nigeria', 'iso_2' => 'NG', 'iso_3' => 'NGA', 'code' => '566'],
    ['name' => 'Niue', 'iso_2' => 'NU', 'iso_3' => 'NIU', 'code' => '570'],
    ['name' => 'Norfolk Island', 'iso_2' => 'NF', 'iso_3' => 'NFK', 'code' => '574'],
    ['name' => 'Northern Mariana Islands', 'iso_2' => 'MP', 'iso_3' => 'MNP', 'code' => '580'],
    ['name' => 'Norway', 'iso_2' => 'NO', 'iso_3' => 'NOR', 'code' => '578'],
    ['name' => 'Oman', 'iso_2' => 'OM', 'iso_3' => 'OMN', 'code' => '512'],
    ['name' => 'Pakistan', 'iso_2' => 'PK', 'iso_3' => 'PAK', 'code' => '586'],
    ['name' => 'Palau', 'iso_2' => 'PW', 'iso_3' => 'PLW', 'code' => '585'],
    ['name' => 'Palestinia', 'iso_2' => 'PS', 'iso_3' => 'PSE', 'code' => '275'],
    ['name' => 'Panama', 'iso_2' => 'PA', 'iso_3' => 'PAN', 'code' => '591'],
    ['name' => 'Papua New Guinea', 'iso_2' => 'PG', 'iso_3' => 'PNG', 'code' => '598'],
    ['name' => 'Paraguay', 'iso_2' => 'PY', 'iso_3' => 'PRY', 'code' => '600'],
    ['name' => 'Peru', 'iso_2' => 'PE', 'iso_3' => 'PER', 'code' => '604'],
    ['name' => 'Philippines', 'iso_2' => 'PH', 'iso_3' => 'PHL', 'code' => '608'],
    ['name' => 'Pitcairn', 'iso_2' => 'PN', 'iso_3' => 'PCN', 'code' => '612'],
    ['name' => 'Poland', 'iso_2' => 'PL', 'iso_3' => 'POL', 'code' => '616'],
    ['name' => 'Portugal', 'iso_2' => 'PT', 'iso_3' => 'PRT', 'code' => '620'],
    ['name' => 'Puerto Rico', 'iso_2' => 'PR', 'iso_3' => 'PRI', 'code' => '630'],
    ['name' => 'Qatar', 'iso_2' => 'QA', 'iso_3' => 'QAT', 'code' => '634'],
    ['name' => 'Reunion', 'iso_2' => 'RE', 'iso_3' => 'REU', 'code' => '638'],
    ['name' => 'Romania', 'iso_2' => 'RO', 'iso_3' => 'ROU', 'code' => '642'],
    ['name' => 'Russian Federation', 'iso_2' => 'RU', 'iso_3' => 'RUS', 'code' => '643'],
    ['name' => 'Rwanda', 'iso_2' => 'RW', 'iso_3' => 'RWA', 'code' => '646'],
    ['name' => 'Saint Helena', 'iso_2' => 'SH', 'iso_3' => 'SHN', 'code' => '654'],
    ['name' => 'Saint Kitts and Nevis', 'iso_2' => 'KN', 'iso_3' => 'KNA', 'code' => '659'],
    ['name' => 'Saint Lucia', 'iso_2' => 'LC', 'iso_3' => 'LCA', 'code' => '662'],
    ['name' => 'Saint Pierre and Miquelon', 'iso_2' => 'PM', 'iso_3' => 'SPM', 'code' => '666'],
    ['name' => 'Saint Vincent and The Grenadines', 'iso_2' => 'VC', 'iso_3' => 'VCT', 'code' => '670'],
    ['name' => 'Samoa', 'iso_2' => 'WS', 'iso_3' => 'WSM', 'code' => '882'],
    ['name' => 'San Marino', 'iso_2' => 'SM', 'iso_3' => 'SMR', 'code' => '674'],
    ['name' => 'Sao Tome and Principe', 'iso_2' => 'ST', 'iso_3' => 'STP', 'code' => '678'],
    ['name' => 'Saudi Arabia', 'iso_2' => 'SA', 'iso_3' => 'SAU', 'code' => '682'],
    ['name' => 'Senegal', 'iso_2' => 'SN', 'iso_3' => 'SEN', 'code' => '686'],
    ['name' => 'Serbia', 'iso_2' => 'RS', 'iso_3' => 'SRB', 'code' => '688'],
    ['name' => 'Seychelles', 'iso_2' => 'SC', 'iso_3' => 'SYC', 'code' => '690'],
    ['name' => 'Sierra Leone', 'iso_2' => 'SL', 'iso_3' => 'SLE', 'code' => '694'],
    ['name' => 'Singapore', 'iso_2' => 'SG', 'iso_3' => 'SGP', 'code' => '702'],
    ['name' => 'Slovakia', 'iso_2' => 'SK', 'iso_3' => 'SVK', 'code' => '703'],
    ['name' => 'Slovenia', 'iso_2' => 'SI', 'iso_3' => 'SVN', 'code' => '705'],
    ['name' => 'Solomon Islands', 'iso_2' => 'SB', 'iso_3' => 'SLB', 'code' => '090'],
    ['name' => 'Somalia', 'iso_2' => 'SO', 'iso_3' => 'SOM', 'code' => '706'],
    ['name' => 'South Africa', 'iso_2' => 'ZA', 'iso_3' => 'ZAF', 'code' => '729'],
    ['name' => 'South Sudan', 'iso_2' => 'SS', 'iso_3' => 'SSD', 'code' => '710'],
    ['name' => 'South Georgia and The South Sandwich Islands', 'iso_2' => 'GS', 'iso_3' => 'SGS', 'code' => '239'],
    ['name' => 'Spain', 'iso_2' => 'ES', 'iso_3' => 'ESP', 'code' => '724'],
    ['name' => 'Sri Lanka', 'iso_2' => 'LK', 'iso_3' => 'LKA', 'code' => '144'],
    ['name' => 'Sudan', 'iso_2' => 'SD', 'iso_3' => 'SDN', 'code' => '736'],
    ['name' => 'Suriname', 'iso_2' => 'SR', 'iso_3' => 'SUR', 'code' => '740'],
    ['name' => 'Svalbard and Jan Mayen', 'iso_2' => 'SJ', 'iso_3' => 'SJM', 'code' => '744'],
    ['name' => 'Swaziland', 'iso_2' => 'SZ', 'iso_3' => 'SWZ', 'code' => '748'],
    ['name' => 'Sweden', 'iso_2' => 'SE', 'iso_3' => 'SWE', 'code' => '752'],
    ['name' => 'Switzerland', 'iso_2' => 'CH', 'iso_3' => 'CHE', 'code' => '756'],
    ['name' => 'Syrian Arab Republic', 'iso_2' => 'SY', 'iso_3' => 'SYR', 'code' => '760'],
    ['name' => 'Taiwan, Province of China', 'iso_2' => 'TW', 'iso_3' => 'TWN', 'code' => '158'],
    ['name' => 'Tajikistan', 'iso_2' => 'TJ', 'iso_3' => 'TJK', 'code' => '762'],
    ['name' => 'Tanzania, United Republic of', 'iso_2' => 'TZ', 'iso_3' => 'TZA', 'code' => '834'],
    ['name' => 'Thailand', 'iso_2' => 'TH', 'iso_3' => 'THA', 'code' => '764'],
    ['name' => 'Timor-leste', 'iso_2' => 'TL', 'iso_3' => 'TLS', 'code' => '626'],
    ['name' => 'Togo', 'iso_2' => 'TG', 'iso_3' => 'TGO', 'code' => '768'],
    ['name' => 'Tokelau', 'iso_2' => 'TK', 'iso_3' => 'TKL', 'code' => '772'],
    ['name' => 'Tonga', 'iso_2' => 'TO', 'iso_3' => 'TON', 'code' => '776'],
    ['name' => 'Trinidad and Tobago', 'iso_2' => 'TT', 'iso_3' => 'TTO', 'code' => '780'],
    ['name' => 'Tunisia', 'iso_2' => 'TN', 'iso_3' => 'TUN', 'code' => '788'],
    ['name' => 'Turkey', 'iso_2' => 'TR', 'iso_3' => 'TUR', 'code' => '792'],
    ['name' => 'Turkmenistan', 'iso_2' => 'TM', 'iso_3' => 'TKM', 'code' => '795'],
    ['name' => 'Turks and Caicos Islands', 'iso_2' => 'TC', 'iso_3' => 'TCA', 'code' => '796'],
    ['name' => 'Tuvalu', 'iso_2' => 'TV', 'iso_3' => 'TUV', 'code' => '798'],
    ['name' => 'Uganda', 'iso_2' => 'UG', 'iso_3' => 'UGA', 'code' => '800'],
    ['name' => 'Ukraine', 'iso_2' => 'UA', 'iso_3' => 'UKR', 'code' => '804'],
    ['name' => 'United Arab Emirates', 'iso_2' => 'AE', 'iso_3' => 'ARE', 'code' => '784'],
    ['name' => 'United Kingdom', 'iso_2' => 'GB', 'iso_3' => 'GBR', 'code' => '826'],
    ['name' => 'United States', 'iso_2' => 'US', 'iso_3' => 'USA', 'code' => '840'],
    ['name' => 'United States Minor Outlying Islands', 'iso_2' => 'UM', 'iso_3' => 'UMI', 'code' => '581'],
    ['name' => 'Uruguay', 'iso_2' => 'UY', 'iso_3' => 'URY', 'code' => '858'],
    ['name' => 'Uzbekistan', 'iso_2' => 'UZ', 'iso_3' => 'UZB', 'code' => '860'],
    ['name' => 'Vanuatu', 'iso_2' => 'VU', 'iso_3' => 'VUT', 'code' => '548'],
    ['name' => 'Venezuela', 'iso_2' => 'VE', 'iso_3' => 'VEN', 'code' => '862'],
    ['name' => 'Vietnam', 'iso_2' => 'VN', 'iso_3' => 'VNM', 'code' => '704'],
    ['name' => 'Virgin Islands, British', 'iso_2' => 'VG', 'iso_3' => 'VGB', 'code' => '092'],
    ['name' => 'Virgin Islands, U.S.', 'iso_2' => 'VI', 'iso_3' => 'VIR', 'code' => '850'],
    ['name' => 'Wallis and Futuna', 'iso_2' => 'WF', 'iso_3' => 'WLF', 'code' => '876'],
    ['name' => 'Western Sahara', 'iso_2' => 'EH', 'iso_3' => 'ESH', 'code' => '732'],
    ['name' => 'Yemen', 'iso_2' => 'YE', 'iso_3' => 'YEM', 'code' => '887'],
    ['name' => 'Zambia', 'iso_2' => 'ZM', 'iso_3' => 'ZMB', 'code' => '894'],
    ['name' => 'Zimbabwe', 'iso_2' => 'ZW', 'iso_3' => 'ZWE', 'code' => '716'],
];
